/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.testng.testng)
    api(libs.com.codeborne.selenide)
    api(libs.com.codeborne.selenide.testng)
    api(libs.org.seleniumhq.selenium.selenium.java)
}

group = "com.epam.ari_kaczmarek.learn"
version = "1.0-SNAPSHOT"
description = "task3"
java.sourceCompatibility = JavaVersion.VERSION_11

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.named<Test>("test") {
    useTestNG {
        setParallel("methods")
        setThreadCount(2)
        val groups: String? by project
        if (groups != null) {
            includeGroups(groups)
        }
    }
}
